baseURL = "https://diegolampre.github.io/Practica_2/"
#baseURL = "https://eejmplo.com"
languageCode = "en-us"
title = "Practica 1"
theme='learn'

[params]
themeVariant="blue"

[outputs]
home=['HTML','JSON','RSS']


